- name: Install Catalogue Service (RHEL 9)
  hosts: localhost
  connection: local
  become: yes
  vars:
    component: catalogue

  tasks:

    # ---------------- BASIC SETUP ---------------- #

    - name: Create test file
      ansible.builtin.file:
        path: /home/test-file
        state: touch

    # ---------------- NODEJS SETUP ---------------- #

    - name: Disable default NodeJS module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable NodeJS 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    # ---------------- USER & DIRECTORY ---------------- #

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        system: yes
        home: /app
        shell: /sbin/nologin

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'

    # ---------------- DOWNLOAD APPLICATION ---------------- #

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Install unzip package
      ansible.builtin.dnf:
        name: unzip
        state: present

    - name: Extract application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install NodeJS dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    # ---------------- SYSTEMD SERVICE ---------------- #

    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: catalouge.service
        dest: /etc/systemd/system/catalogue.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start catalogue service
      ansible.builtin.systemd:
        name: catalogue
        state: started
        enabled: yes

    # ---------------- MONGODB CLIENT ---------------- #

    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB client (mongosh)
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    

    - name: Load MongoDB schema/data
      ansible.builtin.command: mongosh --host mongodb-prod.sndp.online < /app/db/master-data.js 


      