- name: Install catalogue
  hosts: catalogue
  become: yes

  tasks:

    # ---------------- FIX SSL (CRITICAL) ----------------

    - name: Fix crypto policies (prevents SSL error)
      ansible.builtin.shell: |
        update-crypto-policies --set DEFAULT
        dnf update -y openssl curl libcurl ca-certificates
      args:
        executable: /bin/bash

    # ---------------- NODEJS ----------------

    - name: Setup NodeJS 20 repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource*.repo

    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present

    # ---------------- USER ----------------

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop
        system: yes
        home: /app
        shell: /sbin/nologin

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    # ---------------- APP SETUP ----------------

    - name: Download catalogue zip
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Install unzip
      ansible.builtin.dnf:
        name: unzip
        state: present

    - name: Unzip catalogue
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install npm dependencies
      ansible.builtin.npm:
        path: /app

    # ---------------- MONGODB CLIENT ----------------

    - name: Create MongoDB repo file
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/7.0/x86_64/
          gpgcheck=0
          enabled=1

    - name: Install mongosh
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present



    - name: Clean catalogue database
      ansible.builtin.shell: |
        
         mongosh "mongodb://mongodb-prod.sndp.online:27017/catalogue" --eval 'db.products.drop()'

    - name: Load MongoDB data
      ansible.builtin.shell: |
        mongosh "mongodb://mongodb-prod.sndp.online:27017/catalogue" /app/db/master-data.js
      args:
        executable: /bin/bash

    # ---------------- SYSTEMD ----------------

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: catalouge.service
        dest: /etc/systemd/system/catalogue.service

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start catalogue service
      ansible.builtin.systemd:
        name: catalogue
        state: started
        enabled: yes