`; [web]
; 172.31.29.249
#this is ubunutu 

; [ubuntu]
; 3.91.0.150 ansible_user = ubuntu ansible_ssh_private_key_file = ~/.ssh/id_rsa

[local]
localhost ansible_connection=local

[mongodb]
localhost ansible_connection=local

[redis]
localhost ansible_connection=local

[mysql]
localhost ansible_connection=local



 [payment]
localhost ansible_connection=local

 [catalouge]
localhost ansible_connection=local


[user]
 localhost ansible_connection=local


 [cart]
localhost ansible_connection=local

[mysql]
localhost ansible_connection=local

 [frontend]
localhost ansible_connection=local

  [shipping]
localhost ansible_connection=local

[Rabitmq]
localhost ansible_connection=local





