[local]
localhost ansible_connection=local

[mongodb]
localhost ansible_connection=local

[redis]
localhost ansible_connection=local

[mysql]
localhost ansible_connection=local

[payment]
localhost ansible_connection=local

[catalogue]
localhost ansible_connection=local

[user]
localhost ansible_connection=local

[cart]
localhost ansible_connection=local

[frontend]
localhost ansible_connection=local

[shipping]
localhost ansible_connection=local

[rabbitmq]
localhost ansible_connection=local