---
- name: Install MySQL server
  hosts: mysql
  become: yes

  vars:
    mysql_root_password: "RoboShop@1"

  tasks:

    - name: Download MySQL 8 repo
      ansible.builtin.get_url:
        url: https://repo.mysql.com/mysql80-community-release-el7-7.noarch.rpm
        dest: /tmp/mysql80-community-release-el7.rpm

    - name: Install MySQL repo
      ansible.builtin.dnf:
        name: /tmp/mysql80-community-release-el7.rpm
        state: present
        disable_gpg_check: yes

    - name: Disable default MySQL module
      ansible.builtin.command: dnf module disable mysql -y

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Wait for MySQL
      ansible.builtin.wait_for:
        port: 3306
        host: 127.0.0.1
        delay: 5
        timeout: 60

    - name: Install PyMySQL
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present

    - name: Install boto dependencies
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        executable: pip3

    - name: Set root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock